apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: much-todo
type: Opaque
stringData:
  jwt-secret-key: your-super-secret-key-change-in-production-use-strong-random-key
  mongo-username: muchtodousr
  mongo-password: Password!234
  redis-password: ""
