apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-configmap
  namespace: much-todo
data:
  port: "8080"
  log-level: "INFO"
  log-format: "json"
  mongo-host: "mongodb"
  mongo-port: "27017"
  mongo-database: "much_todo_db"
  mongo-replica-set: "rs0"
  redis-host: "redis"
  redis-port: "6379"
  jwt-expiration-hours: "72"
  allowed-origins: "http://localhost:5173,http://localhost:3000,http://localhost:8080"
  cookie-domains: "localhost"
  secure-cookie: "false"
  enable-cache: "true"
